# --- Split Keyboard ---
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# Hall Effect features are automatically enabled by the Devicetree in this module.
# The module requires ZMK_POINTING to be enabled for mouse features.
CONFIG_ZMK_POINTING=y

# --- RGB Underglow ---
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=10
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=40

# --- Power Management ---
CONFIG_ZMK_SLEEP=y
