# Enable RGB
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# The USB port can usually provide 500mA. A strip of WS2812B LEDs can pull 60mA per LED at full brightness white.
# 10 LEDs: 600mA (Pushing the limit of a standard USB 2.0 port).
# Solution: In your config/my_keyboard.conf, limit the maximum brightness:
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=10
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=40

# Power management (Optional but recommended for NRF52840)
CONFIG_ZMK_SLEEP=y

# Core Hall Effect Support
CONFIG_ZMK_HALL_EFFECT=y

# High polling rate for better analog response
CONFIG_USB_HID_POLLING_INTERVAL_MS=1

# Advanced HE Features
CONFIG_ZMK_HE_ADJUSTABLE_ACTUATION=y
CONFIG_ZMK_HE_RAPID_TRIGGER=y
